"""add motivo_no_lectura_id to readings

Revision ID: 156603250476
Revises: bf4a5a34dca2
Create Date: 2026-05-28 14:02:38.293994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156603250476'
down_revision: Union[str, None] = 'bf4a5a34dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('motivo_no_lectura_id', sa.UUID(), nullable=True))
    op.alter_column('readings', 'lectura_actual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_readings_motivo_no_lectura_id'), 'readings', ['motivo_no_lectura_id'], unique=False)
    op.create_foreign_key(None, 'readings', 'no_read_reasons', ['motivo_no_lectura_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.drop_index(op.f('ix_readings_motivo_no_lectura_id'), table_name='readings')
    op.alter_column('readings', 'lectura_actual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('readings', 'motivo_no_lectura_id')
    # ### end Alembic commands ###
