"""add rutas, rutas_asignadas, ruta_id+orden to meters

Revision ID: 3725e175e76b
Revises: 156603250476
Create Date: 2026-05-28 14:08:47.954923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3725e175e76b'
down_revision: Union[str, None] = '156603250476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutas',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_codigo'), 'rutas', ['codigo'], unique=True)
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    op.create_table('rutas_asignadas',
    sa.Column('lector_id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lector_id', 'ruta_id', name='uq_lector_ruta')
    )
    op.create_index(op.f('ix_rutas_asignadas_id'), 'rutas_asignadas', ['id'], unique=False)
    op.create_index(op.f('ix_rutas_asignadas_lector_id'), 'rutas_asignadas', ['lector_id'], unique=False)
    op.create_index(op.f('ix_rutas_asignadas_ruta_id'), 'rutas_asignadas', ['ruta_id'], unique=False)
    op.add_column('meters', sa.Column('ruta_id', sa.UUID(), nullable=True))
    op.add_column('meters', sa.Column('orden', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_meters_ruta_id'), 'meters', ['ruta_id'], unique=False)
    op.create_foreign_key(None, 'meters', 'rutas', ['ruta_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meters', type_='foreignkey')
    op.drop_index(op.f('ix_meters_ruta_id'), table_name='meters')
    op.drop_column('meters', 'orden')
    op.drop_column('meters', 'ruta_id')
    op.drop_index(op.f('ix_rutas_asignadas_ruta_id'), table_name='rutas_asignadas')
    op.drop_index(op.f('ix_rutas_asignadas_lector_id'), table_name='rutas_asignadas')
    op.drop_index(op.f('ix_rutas_asignadas_id'), table_name='rutas_asignadas')
    op.drop_table('rutas_asignadas')
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_index(op.f('ix_rutas_codigo'), table_name='rutas')
    op.drop_table('rutas')
    # ### end Alembic commands ###
