"""change_entidad_id_to_string_in_audit_logs

Revision ID: 47cf202a846b
Revises: f1a2b3c4d5e6
Create Date: 2026-05-30 12:59:16.056224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47cf202a846b'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'entidad_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_historial_lecturas_ID_LECTURA'), table_name='historial_lecturas')
    op.drop_index(op.f('ix_historial_lecturas_ID_PREDIO'), table_name='historial_lecturas')
    op.drop_index(op.f('ix_historial_lecturas_NUIS'), table_name='historial_lecturas')
    op.create_index(op.f('ix_historial_lecturas_id_lectura'), 'historial_lecturas', ['id_lectura'], unique=False)
    op.create_index(op.f('ix_historial_lecturas_id_predio'), 'historial_lecturas', ['id_predio'], unique=False)
    op.create_index(op.f('ix_historial_lecturas_nuis'), 'historial_lecturas', ['nuis'], unique=False)
    op.alter_column('no_read_reasons', 'codigo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('no_read_reasons', 'sugiere_promedio',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('no_read_reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_no_read_reasons_codigo'), 'no_read_reasons', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_no_read_reasons_codigo'), table_name='no_read_reasons')
    op.alter_column('no_read_reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('no_read_reasons', 'sugiere_promedio',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('no_read_reasons', 'codigo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_historial_lecturas_nuis'), table_name='historial_lecturas')
    op.drop_index(op.f('ix_historial_lecturas_id_predio'), table_name='historial_lecturas')
    op.drop_index(op.f('ix_historial_lecturas_id_lectura'), table_name='historial_lecturas')
    op.create_index(op.f('ix_historial_lecturas_NUIS'), 'historial_lecturas', ['nuis'], unique=False)
    op.create_index(op.f('ix_historial_lecturas_ID_PREDIO'), 'historial_lecturas', ['id_predio'], unique=False)
    op.create_index(op.f('ix_historial_lecturas_ID_LECTURA'), 'historial_lecturas', ['id_lectura'], unique=False)
    op.alter_column('audit_logs', 'entidad_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
