"""phase2: sync_jobs, notification_queue, cache_stats, device_id, validacion

Revision ID: 80a20673f451
Revises: b9537ba2534f
Create Date: 2026-05-27 14:36:06.969065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a20673f451'
down_revision: Union[str, None] = 'b9537ba2534f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('max_intentos', sa.Integer(), nullable=False),
    sa.Column('procesado_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_estado'), 'sync_jobs', ['estado'], unique=False)
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('payload_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=False),
    sa.Column('enviado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_id'), 'notification_queue', ['id'], unique=False)
    op.add_column('meters', sa.Column('niud', sa.String(length=50), nullable=True))
    op.add_column('meters', sa.Column('vereda', sa.String(length=100), nullable=True))
    op.add_column('meters', sa.Column('ruta', sa.String(length=100), nullable=True))
    op.add_column('meters', sa.Column('cache_stats', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_meters_niud'), 'meters', ['niud'], unique=True)
    op.create_index(op.f('ix_meters_ruta'), 'meters', ['ruta'], unique=False)
    op.create_index(op.f('ix_meters_vereda'), 'meters', ['vereda'], unique=False)
    op.add_column('readings', sa.Column('device_id', sa.String(length=100), nullable=True))
    op.add_column('readings', sa.Column('estado_validacion', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_readings_estado_validacion'), 'readings', ['estado_validacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_estado_validacion'), table_name='readings')
    op.drop_column('readings', 'estado_validacion')
    op.drop_column('readings', 'device_id')
    op.drop_index(op.f('ix_meters_vereda'), table_name='meters')
    op.drop_index(op.f('ix_meters_ruta'), table_name='meters')
    op.drop_index(op.f('ix_meters_niud'), table_name='meters')
    op.drop_column('meters', 'cache_stats')
    op.drop_column('meters', 'ruta')
    op.drop_column('meters', 'vereda')
    op.drop_column('meters', 'niud')
    op.drop_index(op.f('ix_notification_queue_id'), table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_estado'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###
