"""add foto and sugiere_promedio to no_read_reasons

Revision ID: aefcc82317c6
Revises: ea4c4435af97
Create Date: 2026-05-28 20:35:24.909138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefcc82317c6'
down_revision: Union[str, None] = 'ea4c4435af97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('no_read_reasons', sa.Column('foto', sa.Text(), nullable=True))
    op.add_column('no_read_reasons', sa.Column('sugiere_promedio', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('no_read_reasons', 'sugiere_promedio')
    op.drop_column('no_read_reasons', 'foto')
    # ### end Alembic commands ###
