"""add observacion to historial_lecturas

Revision ID: b15463a1d7c8
Revises: b656b658728f
Create Date: 2026-05-30 19:00:44.329798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15463a1d7c8'
down_revision: Union[str, None] = 'b656b658728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_lecturas', sa.Column('observacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historial_lecturas', 'observacion')
    # ### end Alembic commands ###
