"""add status to historial_lecturas

Revision ID: b656b658728f
Revises: 47cf202a846b
Create Date: 2026-05-30 15:06:52.012020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b656b658728f'
down_revision: Union[str, None] = '47cf202a846b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_lecturas', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE historial_lecturas SET status = 'pendiente'")
    op.alter_column('historial_lecturas', 'status', nullable=False, server_default='pendiente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historial_lecturas', 'status')
    # ### end Alembic commands ###
