"""add no_read_reasons table

Revision ID: bf4a5a34dca2
Revises: 80a20673f451
Create Date: 2026-05-28 14:01:16.724704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a5a34dca2'
down_revision: Union[str, None] = '80a20673f451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_read_reasons',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_no_read_reasons_codigo'), 'no_read_reasons', ['codigo'], unique=True)
    op.create_index(op.f('ix_no_read_reasons_id'), 'no_read_reasons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_no_read_reasons_id'), table_name='no_read_reasons')
    op.drop_index(op.f('ix_no_read_reasons_codigo'), table_name='no_read_reasons')
    op.drop_table('no_read_reasons')
    # ### end Alembic commands ###
