"""add observaciones_admin to readings

Revision ID: e61a5f46d6fa
Revises: 3725e175e76b
Create Date: 2026-05-28 14:17:17.172403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61a5f46d6fa'
down_revision: Union[str, None] = '3725e175e76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('observaciones_admin', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'observaciones_admin')
    # ### end Alembic commands ###
