"""add enhanced reading validation fields

Revision ID: ea4c4435af97
Revises: e61a5f46d6fa
Create Date: 2026-05-28 15:42:44.571819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4c4435af97'
down_revision: Union[str, None] = 'e61a5f46d6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('consumo_calculado', sa.Float(), nullable=True))
    op.add_column('readings', sa.Column('consumo_categoria', sa.String(length=50), nullable=True))
    op.add_column('readings', sa.Column('promedio_historico_usado', sa.Float(), nullable=True))
    op.add_column('readings', sa.Column('timestamp_validacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('readings', sa.Column('usuario_id', sa.UUID(), nullable=True))
    op.add_column('readings', sa.Column('version_app', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_readings_usuario_id'), 'readings', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'readings', 'users', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.drop_index(op.f('ix_readings_usuario_id'), table_name='readings')
    op.drop_column('readings', 'version_app')
    op.drop_column('readings', 'usuario_id')
    op.drop_column('readings', 'timestamp_validacion')
    op.drop_column('readings', 'promedio_historico_usado')
    op.drop_column('readings', 'consumo_categoria')
    op.drop_column('readings', 'consumo_calculado')
    # ### end Alembic commands ###
